on:
  push:
   branches:
    - 'main'
    - 'master'
  pull_request:
    types:
      - 'opened'
      - 'reopened'
  workflow_dispatch:
jobs:
  execute-scan-workflow:
    uses: threatrix/threat-agent-scan/.github/workflows/scan-repo-reusable.yaml@master
    with:
      eid: 5975a169-77fc-414d-8ac1-d5fffc8b9210
      oid: 7b841ffb-b8c6-4973-ba75-28a9a78d0d8f
      app-name: threat-matrix-2
      trx-host: https://app2.threatrix.io
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      THREATRIX_SERVER_API_KEY: ${{ secrets.THREATRIX_API_KEY }}
